// All user-facing auth strings (Indonesian). Keep UI copy here, not inline in screens.
export const Strings = {
  common: {
    error: 'Terjadi kesalahan',
    ok: 'OK',
    networkError: 'Tidak dapat terhubung ke server. Periksa koneksi Anda.',
    unexpectedError: 'Terjadi kesalahan. Silakan coba lagi.',
  },
  auth: {
    appName: 'PillCare',
    welcome: 'Selamat datang di PillCare',
    signInSubtitle: 'Masuk untuk membuka dasbor pendamping',
    signUpSubtitle: 'Buat akun untuk memulai',
    tabSignIn: 'Masuk',
    tabSignUp: 'Daftar',
    fullName: 'Nama lengkap',
    fullNamePlaceholder: 'Masukkan nama lengkap',
    email: 'Email',
    emailPlaceholder: 'Masukkan email',
    phoneNumber: 'Nomor telepon',
    phoneNumberPlaceholder: '+6281234567890',
    password: 'Kata sandi',
    passwordPlaceholder: 'Masukkan kata sandi',
    confirmPassword: 'Konfirmasi kata sandi',
    confirmPasswordPlaceholder: 'Ulangi kata sandi',
    showPassword: 'Tampilkan',
    hidePassword: 'Sembunyikan',
    submitSignIn: 'Masuk',
    submitSignUp: 'Buat akun',
    forgotPasswordLink: 'Lupa kata sandi?',
    or: 'ATAU',
    continueWithGoogle: 'Lanjutkan dengan Google',
    googleUnavailable: 'Masuk dengan Google memerlukan development build (tidak tersedia di Expo Go).',
    signOut: 'Keluar',
    signedInAs: 'Masuk sebagai',
  },
  forgotPassword: {
    title: 'Lupa kata sandi',
    subtitle: 'Masukkan email Anda. Kami akan mengirim kode OTP 6 digit.',
    submit: 'Kirim kode',
    sentTitle: 'Kode terkirim',
    sentMessage: 'Jika email terdaftar, kode OTP telah dikirim. Kode berlaku 10 menit.',
    backToSignIn: 'Kembali ke halaman masuk',
  },
  resetPassword: {
    title: 'Atur ulang kata sandi',
    subtitle: 'Masukkan kode OTP dari email dan kata sandi baru Anda.',
    otp: 'Kode OTP',
    otpPlaceholder: '6 digit',
    newPassword: 'Kata sandi baru',
    submit: 'Simpan kata sandi',
    successTitle: 'Berhasil',
    successMessage: 'Kata sandi berhasil diubah. Silakan masuk kembali.',
  },
  validation: {
    required: 'Semua kolom wajib diisi.',
    passwordMismatch: 'Konfirmasi kata sandi tidak cocok.',
    passwordTooShort: 'Kata sandi minimal 8 karakter.',
    phoneFormat: 'Nomor telepon harus format internasional, mis. +6281234567890.',
    otpFormat: 'Kode OTP harus 6 digit.',
  },
  // Messages for API error codes; unknown codes fall back to common.unexpectedError.
  apiErrors: {
    INVALID_CREDENTIALS: 'Email atau kata sandi salah.',
    EMAIL_ALREADY_REGISTERED: 'Email sudah terdaftar.',
    VALIDATION_ERROR: 'Data yang dimasukkan tidak valid.',
    INVALID_OTP: 'Kode OTP salah atau sudah kedaluwarsa.',
    GOOGLE_TOKEN_INVALID: 'Gagal masuk dengan Google. Silakan coba lagi.',
    NETWORK_ERROR: 'Tidak dapat terhubung ke server. Periksa koneksi Anda.',
    UNAUTHORIZED: 'Sesi Anda telah berakhir. Silakan masuk kembali.',
  } as Record<string, string>,
} as const;
